// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJgsgcdC1QMpO4qVvSNiqcs5xKVaF8-4',
    appId: '1:52441087010:web:ec14ab97bddaf3a41b9e7b',
    messagingSenderId: '52441087010',
    projectId: 'mytestrun12132',
    authDomain: 'mytestrun12132.firebaseapp.com',
    storageBucket: 'mytestrun12132.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYaxO1fSGdrW5fDzPDvqBfWwE6aiEMefY',
    appId: '1:52441087010:android:a9b01f758a550ca91b9e7b',
    messagingSenderId: '52441087010',
    projectId: 'mytestrun12132',
    storageBucket: 'mytestrun12132.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr149PDOoksoD4Q2zunQe0_58kCa_7gtg',
    appId: '1:52441087010:ios:8a603e08257d52611b9e7b',
    messagingSenderId: '52441087010',
    projectId: 'mytestrun12132',
    storageBucket: 'mytestrun12132.appspot.com',
    iosClientId: '52441087010-raed5g315i6pv9db5uthqfotuphpi4e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.testRun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr149PDOoksoD4Q2zunQe0_58kCa_7gtg',
    appId: '1:52441087010:ios:8a603e08257d52611b9e7b',
    messagingSenderId: '52441087010',
    projectId: 'mytestrun12132',
    storageBucket: 'mytestrun12132.appspot.com',
    iosClientId: '52441087010-raed5g315i6pv9db5uthqfotuphpi4e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.testRun',
  );
}
